# Generated by Django 3.0.8 on 2020-08-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprofile',
            name='voter',
            field=models.ManyToManyField(blank=True, related_name='voter_profile', to='proj.User'),
        ),
    ]
