# Generated by Django 3.0.8 on 2020-08-03 07:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0003_auto_20200803_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connections',
            name='registered_date',
        ),
        migrations.AddField(
            model_name='connections',
            name='registered_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='score',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
