# Generated by Django 3.0.8 on 2020-07-30 06:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django_mysql.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proj', '0003_auto_20200727_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proj.PersonalProfile')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id_comment', to=settings.AUTH_USER_MODEL)),
                ('voter', models.ManyToManyField(related_name='voter_comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_date', models.DateField(verbose_name='date published')),
                ('meeting_date', models.DateField()),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='connection_mentee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_company', models.CharField(max_length=20)),
                ('current_job', models.CharField(max_length=20)),
                ('work_period_from', models.DateField()),
                ('work_period_to', models.DateField(default=datetime.datetime(2020, 7, 30, 6, 47, 33, 216520, tzinfo=utc))),
                ('certificates', django_mysql.models.ListCharField(models.CharField(max_length=20), max_length=105, size=5)),
                ('extracurricular', django_mysql.models.ListCharField(models.CharField(max_length=20), max_length=105, size=5)),
                ('work_experience', django_mysql.models.ListCharField(models.CharField(max_length=20), max_length=105, size=5)),
                ('appliedCompanies', django_mysql.models.ListCharField(models.CharField(max_length=20), max_length=63, size=3)),
                ('appliedCompanies_stage', django_mysql.models.ListCharField(models.CharField(default='서류합', max_length=20), max_length=63, size=3)),
                ('PR', models.TextField()),
                ('real_name', models.CharField(max_length=20)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('bank', models.CharField(default='', max_length=20)),
                ('account_num', models.BigIntegerField()),
                ('account_email', models.CharField(default='', max_length=20)),
                ('create_date', models.DateTimeField(verbose_name='date published')),
                ('date_modified', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id_mentor_profile', to=settings.AUTH_USER_MODEL)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_name_mentor_profile', to=settings.AUTH_USER_MODEL)),
                ('voter', models.ManyToManyField(related_name='voter_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(verbose_name='date published')),
                ('granted_by', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('granted_to', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='granted_to', to='proj.MentorProfile')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='connections',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='connection_mentor', to='proj.MentorProfile'),
        ),
    ]
