# Generated by Django 3.0.8 on 2020-07-30 06:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0004_auto_20200730_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprofile',
            name='work_period_to',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
