# Generated by Django 3.0.8 on 2020-08-12 02:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0004_auto_20200803_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connections',
            name='registered_at',
        ),
        migrations.AddField(
            model_name='connections',
            name='registered_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mentorprofileappliedcompanies',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AppliedCompanies', to='proj.MentorProfile'),
        ),
        migrations.AlterField(
            model_name='mentorprofilecertificates',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Certificates', to='proj.MentorProfile'),
        ),
        migrations.AlterField(
            model_name='mentorprofileextracurricular',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Extracurricular', to='proj.MentorProfile'),
        ),
        migrations.AlterField(
            model_name='mentorprofileworkexperience',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WorkExperience', to='proj.MentorProfile'),
        ),
    ]
