# Generated by Django 3.0.8 on 2020-07-31 06:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0005_auto_20200730_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorprofile',
            name='appliedCompanies',
        ),
        migrations.RemoveField(
            model_name='mentorprofile',
            name='appliedCompanies_stage',
        ),
        migrations.RemoveField(
            model_name='mentorprofile',
            name='certificates',
        ),
        migrations.RemoveField(
            model_name='mentorprofile',
            name='extracurricular',
        ),
        migrations.RemoveField(
            model_name='mentorprofile',
            name='work_experience',
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='MentorProfileWorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workexperience', models.CharField(max_length=20)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proj.MentorProfile')),
            ],
        ),
        migrations.CreateModel(
            name='MentorProfileExtracurricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracurricular', models.CharField(max_length=20)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proj.MentorProfile')),
            ],
        ),
        migrations.CreateModel(
            name='MentorProfileCertificates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.CharField(max_length=20)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proj.MentorProfile')),
            ],
        ),
        migrations.CreateModel(
            name='MentorProfileAppliedCompanies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliedcompany', models.CharField(max_length=20)),
                ('appliedcompanystage', models.CharField(default='최종합', max_length=20)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proj.MentorProfile')),
            ],
        ),
    ]
