# Generated by Django 3.0.8 on 2020-08-12 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0005_auto_20200812_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_mentor',
            field=models.BooleanField(default=False),
        ),
    ]
