# Generated by Django 3.0.8 on 2020-07-31 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0006_auto_20200731_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprofile',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
