# Generated by Django 3.0.8 on 2020-07-31 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0007_auto_20200731_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprofile',
            name='work_period_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
