# Generated by Django 3.0.8 on 2020-07-22 08:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mentor', '0007_delete_repl'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='voter',
            field=models.ManyToManyField(related_name='voter_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='voter',
            field=models.ManyToManyField(related_name='voter_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
