# Generated by Django 3.0.8 on 2020-07-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='author',
            field=models.CharField(default='ADE', max_length=100),
            preserve_default=False,
        ),
    ]
