# Generated by Django 3.0.8 on 2020-07-22 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0006_repl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Repl',
        ),
    ]
